/**
 * api.js — HTTP client for the Vial dashboard API.
 *
 * All requests go to the embedded Go server (`internal/dashboard/server.go`)
 * which binds exclusively to 127.0.0.1. Every request must carry a Bearer
 * token that the server validates with crypto/subtle.ConstantTimeCompare,
 * so timing-attack-safe comparison is handled on the Go side.
 *
 * Token lifecycle:
 *   1. The Go server passes the one-time token to the browser via the URL
 *      fragment (#token=<hex>). Fragments are never sent to the server in HTTP
 *      requests, so the token is not exposed in access logs.
 *   2. layout.svelte strips the fragment and persists the token to
 *      sessionStorage via setToken(), so it survives page navigations but not
 *      new browser sessions.
 *   3. Every apiFetch() call reads the token from sessionStorage and injects
 *      it as an Authorization: Bearer header.
 *   4. On a 401 response the token is cleared and an actionable error is
 *      thrown — the user must re-run `vial dashboard` to get a fresh token.
 */

/** Base path prefix. Empty string because the SPA is served from the same
 *  origin as the API, so relative URLs work without a configured hostname. */
const BASE = '';

/**
 * Retrieves the stored auth token from sessionStorage.
 * Returns an empty string when no token exists so Bearer header is always
 * present (the server will reject the empty-string token with 401).
 *
 * @returns {string} The hex token, or '' if not yet authenticated.
 */
function getToken() {
	return sessionStorage.getItem('vial_token') || '';
}

/**
 * Persists the auth token to sessionStorage after it has been extracted from
 * the URL fragment by the layout component.
 *
 * @param {string} token — 32-byte hex string generated by the Go server.
 */
export function setToken(token) {
	sessionStorage.setItem('vial_token', token);
}

/**
 * Removes the token from sessionStorage. Called automatically on a 401
 * response so subsequent API calls fail fast rather than retry with a known-
 * bad token.
 */
export function clearToken() {
	sessionStorage.removeItem('vial_token');
}

/**
 * Returns true when a token is present in sessionStorage. Used by the layout
 * to decide whether to render the full dashboard or the "Not Connected" gate.
 *
 * @returns {boolean}
 */
export function hasToken() {
	return !!getToken();
}

/**
 * Core fetch wrapper for all API calls. Automatically injects the Bearer
 * token, sets Content-Type to JSON, and normalises error handling so every
 * caller receives a consistent Error object.
 *
 * @param {string} path — Path relative to /api, e.g. '/vault/secrets'.
 * @param {RequestInit} [options={}] — Standard fetch options. Headers in
 *   options.headers are merged on top of the defaults; Authorization can be
 *   overridden this way if needed.
 * @returns {Promise<unknown>} Parsed JSON response body.
 * @throws {Error} On 401 (token cleared) or any non-2xx status.
 */
export async function apiFetch(path, options = {}) {
	const token = getToken();
	const res = await fetch(`${BASE}/api${path}`, {
		...options,
		headers: {
			'Content-Type': 'application/json',
			Authorization: `Bearer ${token}`,
			// Caller-supplied headers are spread last so they can override
			// Content-Type for multipart requests, but NOT Authorization.
			...options.headers,
		},
	});

	if (res.status === 401) {
		// The token is no longer valid — either the server was restarted and
		// issued a new token, or the session timed out. Clear storage so the
		// "Not Connected" gate appears and the user gets a clear call to action.
		clearToken();
		throw new Error('Not authenticated — run "vial dashboard" from your terminal');
	}

	if (!res.ok) {
		// Bubble up the server's plaintext error message so UI components can
		// display it directly without an additional parsing step.
		const text = await res.text();
		throw new Error(`${res.status}: ${text.trim()}`);
	}

	return res.json();
}

// ---------------------------------------------------------------------------
// Vault secrets
// Each helper is a thin wrapper over apiFetch so callers stay readable and
// the URL-encoding / method boilerplate lives in one place.
// ---------------------------------------------------------------------------

/** Fetches the full list of secrets (keys + metadata, values redacted). */
export const fetchSecrets = () => apiFetch('/vault/secrets');

/**
 * Fetches metadata for a single secret without revealing its value.
 * @param {string} key — Vault key name.
 */
export const fetchSecret = (key) => apiFetch(`/vault/secrets/${encodeURIComponent(key)}`);

/**
 * Fetches a secret with its plaintext value included in the response.
 * The Go server records a 'reveal' audit event for this call.
 * @param {string} key — Vault key name.
 */
export const revealSecret = (key) =>
	apiFetch(`/vault/secrets/${encodeURIComponent(key)}?reveal=true`);

/**
 * Permanently deletes a secret from the vault.
 * @param {string} key — Vault key name.
 */
export const deleteSecret = (key) =>
	apiFetch(`/vault/secrets/${encodeURIComponent(key)}`, { method: 'DELETE' });

/**
 * Creates a new secret. The vault encrypts the value with AES-256-GCM using
 * a fresh random nonce before writing to disk.
 * @param {string} key — Key name (e.g. OPENAI_API_KEY).
 * @param {string} value — Plaintext secret value.
 */
export const createSecret = (key, value) =>
	apiFetch('/vault/secrets', {
		method: 'POST',
		body: JSON.stringify({ key, value }),
	});

// ---------------------------------------------------------------------------
// Aliases — map variant key names onto canonical vault keys.
// Used by the 5-tier matching engine (tier 3) when a .env.example requests
// a key that doesn't exactly match a vault entry.
// ---------------------------------------------------------------------------

/** Fetches all defined alias mappings. */
export const fetchAliases = () => apiFetch('/aliases');

/**
 * Creates a new alias mapping.
 * @param {string} alias — The variant name (e.g. OPENAI_KEY).
 * @param {string} canonical — The vault key it resolves to (e.g. OPENAI_API_KEY).
 */
export const createAlias = (alias, canonical) =>
	apiFetch('/aliases', {
		method: 'POST',
		body: JSON.stringify({ alias, canonical }),
	});

/**
 * Deletes an alias mapping.
 * @param {string} alias — The alias name to remove.
 */
export const deleteAlias = (alias) =>
	apiFetch(`/aliases/${encodeURIComponent(alias)}`, { method: 'DELETE' });

// ---------------------------------------------------------------------------
// Projects — registered directories that vial pours secrets into.
// ---------------------------------------------------------------------------

/** Fetches all registered project directories. */
export const fetchProjects = () => apiFetch('/projects');

/**
 * Registers a new project directory so `vial pour` can target it.
 * @param {string} path — Absolute filesystem path to the project root.
 */
export const addProject = (path) =>
	apiFetch('/projects', {
		method: 'POST',
		body: JSON.stringify({ path }),
	});

/**
 * Unregisters a project. Secrets poured to its .env file are not removed.
 * @param {string} name — Project name (derived from the directory basename).
 */
export const removeProject = (name) =>
	apiFetch(`/projects/${encodeURIComponent(name)}`, { method: 'DELETE' });

// ---------------------------------------------------------------------------
// Health & audit
// ---------------------------------------------------------------------------

/**
 * Fetches the vault health overview: total counts and per-secret age data
 * used to surface stale secrets that should be rotated.
 */
export const fetchHealth = () => apiFetch('/health/overview');

/**
 * Fetches the audit log: a time-ordered list of vault operations (set,
 * remove, pour, lock/unlock, reveal, etc.) with affected key names.
 */
export const fetchAudit = () => apiFetch('/audit');

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

/**
 * Fetches the active vial configuration (vault_path, session_timeout, etc.)
 * as parsed from ~/.config/vial/config.yaml. Values shown are read-only in
 * the dashboard; users must edit the YAML file directly to change them.
 */
export const fetchConfig = () => apiFetch('/config');

// ---------------------------------------------------------------------------
// Auth
// ---------------------------------------------------------------------------

/**
 * Instructs the Go server to lock the vault (zeroes the in-memory DEK).
 * After locking, any further API calls that require a decrypted vault will
 * fail until the user runs `vial uncork` or the dashboard re-authenticates.
 */
export const lockVault = () => apiFetch('/auth/lock', { method: 'POST' });

/**
 * Returns the current lock state of the vault so the Settings page can
 * display whether the vault is currently unlocked in the server process.
 */
export const authStatus = () => apiFetch('/auth/status');
