package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"

	"github.com/cheesejaguar/vial/internal/scanner"
)

var scaffoldCmd = &cobra.Command{
	Use:   "scaffold [DIR]",
	Short: "Auto-generate .env.example from source code",
	Long: `Scan project source code for environment variable references and generate
a .env.example file. Detects env vars in JavaScript, TypeScript, Python, Go,
Ruby, Rust, and PHP.

If .env.example already exists, merges new variables without removing existing ones.

Examples:
  vial scaffold                # scan current directory
  vial scaffold ./my-project   # scan specific directory
  vial scaffold --overwrite    # replace existing .env.example`,
	Args: cobra.MaximumNArgs(1),
	RunE: runScaffold,
}

var (
	scaffoldOverwrite bool
	scaffoldOutput    string
)

func init() {
	scaffoldCmd.Flags().BoolVar(&scaffoldOverwrite, "overwrite", false, "Overwrite existing .env.example instead of merging")
	scaffoldCmd.Flags().StringVarP(&scaffoldOutput, "output", "o", "", "Output file path (default: .env.example in target dir)")
	rootCmd.AddCommand(scaffoldCmd)
}

func runScaffold(cmd *cobra.Command, args []string) error {
	dir := "."
	if len(args) > 0 {
		dir = args[0]
	}
	absDir, err := filepath.Abs(dir)
	if err != nil {
		return fmt.Errorf("resolving path: %w", err)
	}

	if err := loadConfig(); err != nil {
		return err
	}

	outputPath := scaffoldOutput
	if outputPath == "" {
		outputPath = filepath.Join(absDir, cfg.EnvExample)
	}

	// Scan source code
	fmt.Printf("🔍 Scanning %s for env var references...\n", mutedText(absDir))
	result, err := scanner.ScanDir(absDir)
	if err != nil {
		return fmt.Errorf("scanning: %w", err)
	}

	if len(result.Refs) == 0 {
		fmt.Println(mutedText("No environment variable references found in source code."))
		return nil
	}

	fmt.Printf("  %s\n", result.Summary())

	// Build unique vars with source references
	type varInfo struct {
		name  string
		files []string
	}
	varMap := make(map[string]*varInfo)
	for _, ref := range result.Refs {
		relPath, _ := filepath.Rel(absDir, ref.File)
		if relPath == "" {
			relPath = ref.File
		}
		loc := fmt.Sprintf("%s:%d", relPath, ref.Line)
		if vi, ok := varMap[ref.Name]; ok {
			// Deduplicate file references
			found := false
			for _, f := range vi.files {
				if f == loc {
					found = true
					break
				}
			}
			if !found {
				vi.files = append(vi.files, loc)
			}
		} else {
			varMap[ref.Name] = &varInfo{name: ref.Name, files: []string{loc}}
		}
	}

	// Sort variable names for deterministic output
	varNames := make([]string, 0, len(varMap))
	for name := range varMap {
		varNames = append(varNames, name)
	}
	sort.Strings(varNames)

	// Load existing .env.example if merging
	existingKeys := make(map[string]bool)
	var existingContent string
	if !scaffoldOverwrite {
		if data, err := os.ReadFile(outputPath); err == nil {
			existingContent = string(data)
			for _, line := range strings.Split(existingContent, "\n") {
				line = strings.TrimSpace(line)
				if line == "" || strings.HasPrefix(line, "#") {
					continue
				}
				if idx := strings.Index(line, "="); idx > 0 {
					existingKeys[line[:idx]] = true
				}
			}
		}
	}

	// Build new content
	var lines []string

	if existingContent != "" && !scaffoldOverwrite {
		// Merge mode: append new vars to existing file
		lines = append(lines, strings.TrimRight(existingContent, "\n"))

		var newVars []string
		for _, name := range varNames {
			if !existingKeys[name] {
				newVars = append(newVars, name)
			}
		}

		if len(newVars) == 0 {
			fmt.Println("  .env.example is already up to date — no new vars found.")
			return nil
		}

		lines = append(lines, "")
		lines = append(lines, "# Auto-discovered by vial scaffold")
		for _, name := range newVars {
			vi := varMap[name]
			lines = append(lines, fmt.Sprintf("# Used in: %s", strings.Join(vi.files, ", ")))
			lines = append(lines, name+"=")
		}

		fmt.Printf("  %s Added %s new variable(s) to %s\n", successIcon(), countText(fmt.Sprintf("%d", len(newVars))), filepath.Base(outputPath))
	} else {
		// Fresh generation
		lines = append(lines, "# Environment variables for "+filepath.Base(absDir))
		lines = append(lines, "# Generated by: vial scaffold")
		lines = append(lines, "# Source: scanned project source code")
		lines = append(lines, "")

		for i, name := range varNames {
			vi := varMap[name]
			lines = append(lines, fmt.Sprintf("# Used in: %s", strings.Join(vi.files, ", ")))
			lines = append(lines, name+"=")
			if i < len(varNames)-1 {
				lines = append(lines, "")
			}
		}

		fmt.Printf("  %s Generated %s with %s variable(s)\n", successIcon(), boldText(filepath.Base(outputPath)), countText(fmt.Sprintf("%d", len(varNames))))
	}

	content := strings.Join(lines, "\n") + "\n"
	if err := os.WriteFile(outputPath, []byte(content), 0600); err != nil {
		return fmt.Errorf("writing %s: %w", outputPath, err)
	}

	fmt.Printf("  %s %s\n", arrowIcon(), mutedText(outputPath))
	return nil
}
