package cli

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"

	"github.com/cheesejaguar/vial/internal/hook"
	"github.com/cheesejaguar/vial/internal/scanner"
)

var setupCmd = &cobra.Command{
	Use:   "setup [DIR]",
	Short: "One-command project onboarding",
	Long: `Zero-config project setup: scan source code, generate .env.example,
register in shelf, pour secrets, and install git hooks — all in one command.

Steps performed:
  1. Scan source code for env var references
  2. Generate .env.example if missing
  3. Register project in shelf
  4. Pour secrets from vault
  5. Install git pre-commit hook (if .git/ exists)

Examples:
  vial setup                 # set up current directory
  vial setup ./my-project    # set up specific project
  vial setup --yes           # non-interactive mode`,
	Args: cobra.MaximumNArgs(1),
	RunE: runSetup,
}

var setupYes bool

func init() {
	setupCmd.Flags().BoolVar(&setupYes, "yes", false, "Non-interactive mode: accept all defaults")
	rootCmd.AddCommand(setupCmd)
}

func runSetup(cmd *cobra.Command, args []string) error {
	dir := "."
	if len(args) > 0 {
		dir = args[0]
	}
	absDir, err := filepath.Abs(dir)
	if err != nil {
		return fmt.Errorf("resolving path: %w", err)
	}

	if err := loadConfig(); err != nil {
		return err
	}

	fmt.Printf("Setting up project: %s\n\n", absDir)

	// Step 1: Scan source code
	fmt.Println("① Scanning source code for env var references...")
	result, err := scanner.ScanDir(absDir)
	if err != nil {
		fmt.Printf("  ⊘ Scan failed: %v\n", err)
	} else if len(result.Refs) > 0 {
		fmt.Printf("  %s\n", result.Summary())
	} else {
		fmt.Println("  No env var references found in source code.")
	}

	// Step 2: Generate .env.example if missing
	templatePath := filepath.Join(absDir, cfg.EnvExample)
	if _, err := os.Stat(templatePath); os.IsNotExist(err) {
		if result != nil && len(result.Refs) > 0 {
			fmt.Printf("\n② Generating %s...\n", cfg.EnvExample)
			if err := runScaffoldForDir(absDir, result); err != nil {
				fmt.Printf("  ⊘ Failed: %v\n", err)
			} else {
				fmt.Printf("  ✓ Generated %s\n", cfg.EnvExample)
			}
		} else {
			fmt.Printf("\n② No env vars found; skipping %s generation\n", cfg.EnvExample)
		}
	} else {
		fmt.Printf("\n② %s already exists\n", cfg.EnvExample)
	}

	// Step 3: Register project in shelf
	fmt.Println("\n③ Registering project in shelf...")
	reg, err := getRegistry()
	if err != nil {
		fmt.Printf("  ⊘ Registry error: %v\n", err)
	} else {
		p, err := reg.Add(absDir)
		if err != nil {
			fmt.Printf("  ⊘ Already registered or error: %v\n", err)
		} else {
			fmt.Printf("  ✓ Registered %s\n", p.Name)
		}
	}

	// Step 4: Pour secrets
	if _, err := os.Stat(templatePath); err == nil {
		fmt.Println("\n④ Pouring secrets from vault...")
		vm, err := requireUnlockedVault()
		if err != nil {
			fmt.Printf("  ⊘ Vault error: %v\n", err)
		} else {
			if err := pourProject(vm, absDir); err != nil {
				fmt.Printf("  ⊘ Pour error: %v\n", err)
			}
			vm.Lock()
		}
	} else {
		fmt.Printf("\n④ No %s found; skipping pour\n", cfg.EnvExample)
	}

	// Step 5: Install git hook
	gitDir := filepath.Join(absDir, ".git")
	if _, err := os.Stat(gitDir); err == nil {
		if !hook.IsInstalled(absDir) {
			fmt.Println("\n⑤ Installing git pre-commit hook...")
			if err := hook.Install(absDir); err != nil {
				fmt.Printf("  ⊘ Hook error: %v\n", err)
			} else {
				fmt.Println("  ✓ Pre-commit hook installed")
			}
		} else {
			fmt.Println("\n⑤ Git hook already installed")
		}
	} else {
		fmt.Println("\n⑤ No .git directory; skipping hook installation")
	}

	fmt.Println("\n→ Project setup complete!")
	return nil
}

// runScaffoldForDir generates .env.example from scan results.
func runScaffoldForDir(absDir string, result *scanner.ScanResult) error {
	varNames := result.UniqueVarNames()
	if len(varNames) == 0 {
		return nil
	}

	outputPath := filepath.Join(absDir, cfg.EnvExample)

	var lines []string
	lines = append(lines, "# Environment variables for "+filepath.Base(absDir))
	lines = append(lines, "# Generated by: vial setup")
	lines = append(lines, "")

	for i, name := range varNames {
		lines = append(lines, name+"=")
		if i < len(varNames)-1 {
			lines = append(lines, "")
		}
	}

	content := ""
	for _, line := range lines {
		content += line + "\n"
	}

	return os.WriteFile(outputPath, []byte(content), 0600)
}
